// Auto-generated by hand to match supabase/migrations/0001-0007.
// Regenerate with `npm run types:supabase` once Docker Desktop is available
// (the supabase CLI requires Docker for `gen types --db-url`).
//
// Schema source of truth: supabase/migrations/*.sql
// Project ref: utcoyyluspvcnyqkrvwy

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      kids: {
        Row: {
          id: string;
          display_name: string;
          avatar_url: string | null;
          primary_team_id: string | null;
          token_hash: string;
          elo: number;
          floor: number;
          card_color_hex: string | null;
          tagline: string | null;
          created_at: string;
          created_by_admin_id: string | null;
        };
        Insert: {
          id?: string;
          display_name: string;
          avatar_url?: string | null;
          primary_team_id?: string | null;
          token_hash: string;
          elo?: number;
          floor?: number;
          card_color_hex?: string | null;
          tagline?: string | null;
          created_at?: string;
          created_by_admin_id?: string | null;
        };
        Update: {
          id?: string;
          display_name?: string;
          avatar_url?: string | null;
          primary_team_id?: string | null;
          token_hash?: string;
          elo?: number;
          floor?: number;
          card_color_hex?: string | null;
          tagline?: string | null;
          created_at?: string;
          created_by_admin_id?: string | null;
        };
        Relationships: [];
      };
      teams: {
        Row: {
          id: string;
          name: string;
          color_hex: string;
          logo_url: string | null;
          created_by_kid_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          color_hex: string;
          logo_url?: string | null;
          created_by_kid_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          color_hex?: string;
          logo_url?: string | null;
          created_by_kid_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      team_members: {
        Row: {
          team_id: string;
          kid_id: string;
          joined_at: string;
        };
        Insert: {
          team_id: string;
          kid_id: string;
          joined_at?: string;
        };
        Update: {
          team_id?: string;
          kid_id?: string;
          joined_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          kid_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          kid_id: string;
          endpoint: string;
          p256dh: string;
          auth: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          kid_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      bey_parts: {
        Row: {
          id: string;
          kind: Database['public']['Enums']['bey_part_kind'];
          name: string;
          stat_attack: number | null;
          stat_defense: number | null;
          stat_stamina: number | null;
          stat_burst_resistance: number | null;
          image_url: string | null;
          source_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          kind: Database['public']['Enums']['bey_part_kind'];
          name: string;
          stat_attack?: number | null;
          stat_defense?: number | null;
          stat_stamina?: number | null;
          stat_burst_resistance?: number | null;
          image_url?: string | null;
          source_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          kind?: Database['public']['Enums']['bey_part_kind'];
          name?: string;
          stat_attack?: number | null;
          stat_defense?: number | null;
          stat_stamina?: number | null;
          stat_burst_resistance?: number | null;
          image_url?: string | null;
          source_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      beys: {
        Row: {
          id: string;
          name_en: string;
          name_de: string | null;
          name_jp: string | null;
          product_code: string | null;
          image_url: string | null;
          type: Database['public']['Enums']['bey_type'] | null;
          line: Database['public']['Enums']['bey_line'] | null;
          blade_id: string | null;
          ratchet_id: string | null;
          bit_id: string | null;
          stat_attack: number | null;
          stat_defense: number | null;
          stat_stamina: number | null;
          stat_burst_resistance: number | null;
          source_url: string | null;
          available_in_de: boolean;
          canonical: boolean;
          scraped_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_de?: string | null;
          name_jp?: string | null;
          product_code?: string | null;
          image_url?: string | null;
          type?: Database['public']['Enums']['bey_type'] | null;
          line?: Database['public']['Enums']['bey_line'] | null;
          blade_id?: string | null;
          ratchet_id?: string | null;
          bit_id?: string | null;
          stat_attack?: number | null;
          stat_defense?: number | null;
          stat_stamina?: number | null;
          stat_burst_resistance?: number | null;
          source_url?: string | null;
          available_in_de?: boolean;
          canonical?: boolean;
          scraped_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_de?: string | null;
          name_jp?: string | null;
          product_code?: string | null;
          image_url?: string | null;
          type?: Database['public']['Enums']['bey_type'] | null;
          line?: Database['public']['Enums']['bey_line'] | null;
          blade_id?: string | null;
          ratchet_id?: string | null;
          bit_id?: string | null;
          stat_attack?: number | null;
          stat_defense?: number | null;
          stat_stamina?: number | null;
          stat_burst_resistance?: number | null;
          source_url?: string | null;
          available_in_de?: boolean;
          canonical?: boolean;
          scraped_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      kid_beys: {
        Row: {
          kid_id: string;
          bey_id: string;
          acquired_at: string;
          nickname: string | null;
        };
        Insert: {
          kid_id: string;
          bey_id: string;
          acquired_at?: string;
          nickname?: string | null;
        };
        Update: {
          kid_id?: string;
          bey_id?: string;
          acquired_at?: string;
          nickname?: string | null;
        };
        Relationships: [];
      };
      battles: {
        Row: {
          id: string;
          logger_kid_id: string;
          winner_kid_id: string;
          loser_kid_id: string;
          winner_score: number;
          loser_score: number;
          winner_bey_id: string | null;
          loser_bey_id: string | null;
          status: Database['public']['Enums']['battle_status'];
          logged_at: string;
          confirmed_at: string | null;
          voided_at: string | null;
          voided_reason: string | null;
          dispute_window_ends_at: string;
        };
        Insert: {
          id?: string;
          logger_kid_id: string;
          winner_kid_id: string;
          loser_kid_id: string;
          winner_score: number;
          loser_score: number;
          winner_bey_id?: string | null;
          loser_bey_id?: string | null;
          status?: Database['public']['Enums']['battle_status'];
          logged_at?: string;
          confirmed_at?: string | null;
          voided_at?: string | null;
          voided_reason?: string | null;
          dispute_window_ends_at?: string;
        };
        Update: {
          id?: string;
          logger_kid_id?: string;
          winner_kid_id?: string;
          loser_kid_id?: string;
          winner_score?: number;
          loser_score?: number;
          winner_bey_id?: string | null;
          loser_bey_id?: string | null;
          status?: Database['public']['Enums']['battle_status'];
          logged_at?: string;
          confirmed_at?: string | null;
          voided_at?: string | null;
          voided_reason?: string | null;
          dispute_window_ends_at?: string;
        };
        Relationships: [];
      };
      battle_rounds: {
        Row: {
          battle_id: string;
          round_number: number;
          finish_type: Database['public']['Enums']['finish_type'];
          winner_kid_id: string;
          points: number;
        };
        Insert: {
          battle_id: string;
          round_number: number;
          finish_type: Database['public']['Enums']['finish_type'];
          winner_kid_id: string;
          points: number;
        };
        Update: {
          battle_id?: string;
          round_number?: number;
          finish_type?: Database['public']['Enums']['finish_type'];
          winner_kid_id?: string;
          points?: number;
        };
        Relationships: [];
      };
      disputes: {
        Row: {
          id: string;
          battle_id: string;
          disputer_kid_id: string;
          reason_code: Database['public']['Enums']['dispute_reason'];
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          battle_id: string;
          disputer_kid_id: string;
          reason_code: Database['public']['Enums']['dispute_reason'];
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          battle_id?: string;
          disputer_kid_id?: string;
          reason_code?: Database['public']['Enums']['dispute_reason'];
          note?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          kid_id: string;
          kind: Database['public']['Enums']['notification_kind'];
          payload_json: Json;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          kid_id: string;
          kind: Database['public']['Enums']['notification_kind'];
          payload_json?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          kid_id?: string;
          kind?: Database['public']['Enums']['notification_kind'];
          payload_json?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      milestones: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          icon_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          icon_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          icon_url?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      kid_milestones: {
        Row: {
          kid_id: string;
          milestone_id: string;
          unlocked_at: string;
        };
        Insert: {
          kid_id: string;
          milestone_id: string;
          unlocked_at?: string;
        };
        Update: {
          kid_id?: string;
          milestone_id?: string;
          unlocked_at?: string;
        };
        Relationships: [];
      };
      stickers: {
        Row: {
          id: string;
          code: string;
          name: string;
          emoji_or_image: string;
          rarity: Database['public']['Enums']['sticker_rarity'];
          min_floor_to_send: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          emoji_or_image: string;
          rarity: Database['public']['Enums']['sticker_rarity'];
          min_floor_to_send?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          emoji_or_image?: string;
          rarity?: Database['public']['Enums']['sticker_rarity'];
          min_floor_to_send?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      endorsements: {
        Row: {
          id: string;
          from_kid_id: string;
          to_kid_id: string;
          sticker_id: string;
          after_battle_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          from_kid_id: string;
          to_kid_id: string;
          sticker_id: string;
          after_battle_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          from_kid_id?: string;
          to_kid_id?: string;
          sticker_id?: string;
          after_battle_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      app_kid_id: {
        Args: Record<string, never>;
        Returns: string | null;
      };
      app_is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
    };
    Enums: {
      bey_type: 'attack' | 'defense' | 'stamina' | 'balance';
      bey_line: 'basic' | 'custom' | 'unique';
      bey_part_kind: 'blade' | 'ratchet' | 'bit';
      battle_status: 'pending' | 'confirmed' | 'voided';
      finish_type: 'spin' | 'over' | 'burst' | 'extreme';
      dispute_reason:
        | 'wrong_score'
        | 'didnt_happen'
        | 'wrong_opponent'
        | 'wrong_bey'
        | 'other';
      notification_kind:
        | 'battle_confirmed'
        | 'battle_voided'
        | 'rank_up'
        | 'dispute_against_you'
        | 'new_endorsement'
        | 'milestone_unlocked'
        | 'admin_msg';
      sticker_rarity: 'common' | 'rare' | 'legendary';
    };
    CompositeTypes: Record<string, never>;
  };
}
